spring:
  activemq:
    broker-url: tcp://localhost:61616
    pool:
      enabled: true
      max-connections: 10

max:
  concurrent:
    consumers: 2

inbound:
  endpoint: jms:INBOUND.D

outbound:
  loop:
    count: 5
  endpoint: jms:OUTBOUND.D
